### ISSUE TITLE
Error: ENOENT, no such file or directory ... traceur

### ISSUE THREAD

**Issue by jwlrs** [filearts/plunker_run#2]
So after I reported issue 1 I retrograded node to v10 and now I got a different error:

```
path.existsSync is now called `fs.existsSync`.

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/USER/SOMEDIR/plunker/plunker_run/compilers/../node_modules/traceur/src/runtime/runtime.js'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/Users/USER/SOMEDIR/plunker/plunker_run/compilers/traceur.coffee:24:16)
    at Object.<anonymous> (/Users/USER/SOMEDIR/plunker/plunker_run/compilers/traceur.coffee:56:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/USER/SOMEDIR/plunker/plunker_run/index.coffee:206:14)
    at Object.<anonymous> (/Users/USER/SOMEDIR/plunker/plunker_run/index.coffee:403:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/USER/SOMEDIR/plunker/plunker_run/server.js:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Which I got around by changing line 15 of https://github.com/filearts/plunker_run/blob/master/compilers/traceur.coffee to 

```
runtime = fs.readFileSync(__dirname + "/../node_modules/traceur/bin/traceur-runtime.js", "utf8")
```

However, fixing this leads to another problem:

```
path.existsSync is now called `fs.existsSync`.

/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:636:9)
    at token_error (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:644:9)
    at expect_token (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:657:9)
    at expect (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:660:36)
    at function_ (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:900:9)
    at /Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:1172:33
    at /Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:683:24
    at expr_atom (/Users/USER/SOMEDIR/plunker/plunker_run/node_modules/uglify-js/lib/parse.js:1117:35)
```

**Comment by mc007** [comment]
that's not fixing it with latest master.
